openapi: 3.1.0
info:
  title: AI Todo Chatbot API
  description: Chat API endpoints for the AI Todo Chatbot feature
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /chat/conversations:
    post:
      summary: Create a new conversation
      operationId: createConversation
      tags: [Chat]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          description: Maximum conversations reached (100)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized

    get:
      summary: List user conversations
      operationId: listConversations
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '401':
          description: Unauthorized

  /chat/conversations/{conversationId}:
    get:
      summary: Get conversation with messages
      operationId: getConversation
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversation with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationWithMessagesResponse'
        '404':
          description: Conversation not found
        '401':
          description: Unauthorized

    delete:
      summary: Delete a conversation
      operationId: deleteConversation
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversation deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Conversation not found
        '401':
          description: Unauthorized

  /chat/conversations/{conversationId}/messages:
    post:
      summary: Send a message and get AI response
      operationId: sendMessage
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '200':
          description: AI response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Message too long (>1000 chars)
        '404':
          description: Conversation not found
        '429':
          description: Rate limit exceeded (5 messages/minute)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized

  /chat/conversations/{conversationId}/title:
    post:
      summary: Generate AI title for conversation
      operationId: generateTitle
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Title generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
        '404':
          description: Conversation not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SendMessageRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          maxLength: 1000
          description: Message content
        language:
          type: string
          enum: [en-US, ur-PK]
          default: en-US
          description: Input language hint

    MessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant, system]
        content:
          type: string
        agent_name:
          type: string
          nullable: true
        agent_icon:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time

    ChatResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/MessageResponse'
        agent_name:
          type: string
          description: Name of the responding agent
        agent_icon:
          type: string
          description: Icon of the responding agent (emoji)

    ConversationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ConversationWithMessagesResponse:
      allOf:
        - $ref: '#/components/schemas/ConversationResponse'
        - type: object
          properties:
            messages:
              type: array
              items:
                $ref: '#/components/schemas/MessageResponse'

    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
